name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Docker Login
      # You may pin to the exact commit or the version.
      # uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772
      uses: docker/login-action@v3.4.0
      with:
        # Server address of Docker registry. If not set then will default to Docker Hub
        registry: ${{ secrets.DOCKER_REGISTRY_URL }}
        # Username used to log against the Docker registry
        username: ${{ secrets.DOCKER_REGISTRY_USER }}
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.DOCKER_REGISTRY_PASSWD }}
        # Specifies whether the given registry is ECR (auto, true or false)
        #ecr: # optional, default is auto
        # Log out from the Docker registry at the end of a job
        logout: true
    - name: Build the Docker image
      env:
        REGISTRY_URL: ${{ secrets.DOCKER_REGISTRY_URL }}
        REGISTRY_USER: ${{ secrets.DOCKER_REGISTRY_USER }}
      run: |
        TODAY_DATE="$(date +%s)"
        IMAGE_NAME="$REGISTRY_URL/$REGISTRY_USER/tarefas-app/tarefas-api:$TODAY_DATE"
        docker build . --file Dockerfile --tag "$IMAGE_NAME"
        echo "$IMAGE_NAME"
        docker push $IMAGE_NAME
